name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://opensuse/amd64:42.1
    
    - name: Install dependencies
      run: make
      
    
