name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: ${{matrix.vector.image}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vector:
        - image: ubuntu
        - image: debian
        - image: opensuse/leap
        - image: opensuse/tumbleweed
    container: ${{matrix.vector.image}}
    steps:
      - uses: actions/checkout@v3
      - run: |
          case "${{matrix.vector.image}}" in
            *"suse"*)
              zypper -n install make gcc kernel-default-devel tar
              ;;
            *"ubuntu"*)
              apt update && apt search linux-headers- && apt install -y make gcc kernel-default-devel linux-headers-generic
              ;;
            *"debian"*)
              apt update && apt search linux-headers- && apt install -y make gcc kernel-default-devel linux-headers-amd64
              ;;
          esac       
      - run: |
          make
          
    
