name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: ${{matrix.vector.image}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vector:
        - image: ubuntu
        - image: debian
        - image: opensuse/leap
        - image: opensuse/tumbleweed
    container: ${{matrix.vector.image}}
    steps:
      - run: |
          if [[ ${{matrix.vector.image}} == *"suse"* ]]; then
            zypper -n install make gcc kernel-default-devel
          else
            apt install -y make gcc kernel-default-devel linux-headers-5.15.0-56-generic
          fi       
      - run: |
          make
          
    
